apiVersion: v1
kind: Pod
metadata:
  name: mypodsecret1
  labels:
    app: nginx
spec:
  containers:
  - name: mypodsecret
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: cred
      mountPath: "/usr/share/nginx/html"
      readOnly: true
  volumes:
  - name: cred
    secret:
      secretName: credenciales
