apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset2
spec:
  replicas: 10
  selector:
   matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
